// Single source of truth for site copy and links.
// Direction B keeps copy minimal — every word earns its place.

export type CaseKind = 'company' | 'bet' | 'initiative' | 'portfolio' | 'exit';

// Editorial reveal payload. When a card or row carries one, clicking it
// opens the EditorialReveal panel instead of navigating.
export type InfoCardItem = {
  slug: string;
  title: string;
  category?: string;
  description: string;
  role?: string;
  theme?: string;
  status?: string;
  year?: string;
  href?: string;
  visualLabel?: string;
};

export type Case = {
  slug: string;
  kind: CaseKind;
  name: string;
  built: string;        // Headline shown on card
  year: string;
  status: string;       // Status badge: "Active" / "Exit" etc.
  image: string;
  href: string;
  description: string;  // Reveal copy on active/hover/focus
  imageAlt?: string;
  primary?: boolean;
  muted?: boolean;
  reveal?: InfoCardItem;
};

export const content = {
  meta: {
    name: 'Andreas Grape',
    location: 'Stockholm',
    year: '2026',
    email: 'andreas@nordicangels.com',
    linkedin: 'https://www.linkedin.com/in/grapeandreas/',
  },

  hero: {
    sentence: 'Building infrastructure for the Nordic private capital market.',
    ctas: [] as { label: string; href: string }[],
  },

  background: {
    eyebrow: 'Background',
    milestones: [
      'Built an IT consulting company from scratch. Scaled. Exited.',
      'Early investor in Academic Work. Now Scandinavia’s largest staffing company.',
      'Co-founder of Nordic Angels. The investor network that runs the Nordic angel layer.',
      'Co-owner of Angel House. A private members club for angels and creatives.',
      'Now building the operating system for the Nordic private capital market.',
    ],
  },

  nordicAngelsOverview: {
    eyebrow: 'Nordic Angels',
    title: 'Operating system for the Nordic private capital market.',
    body: 'Co-founded with Ash Pournouri in 2020. The institutional layer that connects Nordic angels, founders, and the capital that scales them. Seven business lines run on top of it.',
    layers: [
      {
        slug: 'na-network',
        title: 'Nordic Angels',
        category: 'The network',
        description: 'The high-trust angel network. Founded with Ash Pournouri during the pandemic to unite business angels and empower the Nordic startup ecosystem. Now a full-service powerhouse spanning platform, media, events, insight reports, community, deal flow, and capital infrastructure.',
        href: 'https://nordicangels.com/',
      },
      {
        slug: 'na-angel-house',
        title: 'Angel House',
        category: 'The home',
        description: 'Private members club for angels and creatives. The operational base where Nordic angels, founders, and operators gather in person.',
        href: 'https://www.angelhouse.se/',
      },
      {
        slug: 'na-mingla',
        title: 'Mingla',
        category: 'The room',
        description: 'Software for the events where capital and talent are supposed to meet, and usually don’t. Gamified networking that moves guests from passive to active.',
        href: 'https://mingla.io/',
      },
      {
        slug: 'na-nordisia',
        title: 'Nordisia',
        category: 'Capital meets real estate',
        description: 'A platform matching Nordic private capital with high-performing real estate development at institutional standards.',
        href: 'https://nordisia.se/',
      },
      {
        slug: 'na-secondry',
        title: 'Secondry',
        category: 'Private market secondaries',
        description: 'The gateway to Nordic private market secondaries. The layer that has been missing for two decades.',
        href: 'https://www.secondry.com/',
      },
      {
        slug: 'na-snoboll',
        title: 'Snöboll',
        category: 'Angel co-investing',
        description: 'The rails Nordic angels use to invest as a group. Terms, allocation, follow-on, syndicates and SPVs in one place.',
      },
      {
        slug: 'na-advisory',
        title: 'Angel Advisory',
        category: 'Corporate finance',
        description: 'Bridging the angel world with corporate finance. Advisory for the moment angel-backed companies graduate to institutional rounds, M&A, and beyond. Operates as Nordic Angel Office and Nordic Corporate Finance.',
        href: 'https://angeladvisory.com/',
      },
    ] satisfies readonly InfoCardItem[],
    link: { label: 'Visit Nordic Angels', href: 'https://nordicangels.com/' },
  },

  // Cases grouped at render-time by `kind`. Order in this array does not
  // determine chapter order — chapters are composed in PortfolioNarrative.
  portfolio: {
    title: "What I've built.",
    summary: 'Eight companies · two bets · four initiatives',
    cases: [
      // --- Companies Founded --------------------------------------------
      { slug: 'nordic-angels', kind: 'company', name: 'Nordic Angels',
        built: 'The investor network that runs the Nordic angel layer.',
        description: 'Co-founded with Ash Pournouri in 2020. The institutional layer connecting Nordic angels to the companies that need them.',
        year: '2020 →', status: 'Active',
        image: '',
        href: 'https://nordicangels.com/', primary: true,
        reveal: { slug: 'nordic-angels', title: 'Nordic Angels', category: 'Companies founded',
          theme: 'Network · Capital infrastructure', role: 'Co-founder', status: 'Active', year: '2020 →',
          description: 'Co-founded with Ash Pournouri in 2020. The institutional layer connecting Nordic angels, founders, and the capital that scales them. Now a full-service powerhouse spanning platform, media, events, insight reports, deal flow, syndicates, and corporate finance.',
          href: 'https://nordicangels.com/' } },
      { slug: 'angel-house', kind: 'company', name: 'Angel House',
        built: 'A private members club for angels and creatives.',
        description: 'Opened in Stockholm 2025. The operational base where Nordic angels, founders, and creatives gather in person.',
        year: '2025 →', status: 'Active',
        image: '',
        href: 'https://www.angelhouse.se/',
        reveal: { slug: 'angel-house', title: 'Angel House', category: 'Companies founded',
          theme: 'Members club · Community', role: 'Co-owner', status: 'Active', year: '2025 →',
          description: 'A private members club for angels and creatives. Opened in Stockholm 2025 as the operational base where Nordic angels, founders, and creatives gather in person.',
          href: 'https://www.angelhouse.se/' } },
      { slug: 'mingla', kind: 'company', name: 'Mingla',
        built: 'Gamified networking. Move your guests from passive to active.',
        description: 'Software for the events and gatherings where capital and talent are supposed to meet, and usually don’t.',
        year: '2023 →', status: 'Active',
        image: '',
        href: 'https://mingla.io/',
        reveal: { slug: 'mingla', title: 'Mingla', category: 'Companies founded',
          theme: 'Events software', role: 'Co-founder', status: 'Active', year: '2023 →',
          description: 'Gamified networking software for the events and gatherings where capital and talent are supposed to meet, and usually don’t. Move your guests from passive to active.',
          href: 'https://mingla.io/' } },
      { slug: 'nordisia', kind: 'company', name: 'Nordisia',
        built: 'Connecting capital with high-performing real estate development.',
        description: 'A platform for matching Nordic private capital with real estate opportunities at institutional standards.',
        year: '2024 →', status: 'Active',
        image: '',
        href: 'https://nordisia.se/',
        reveal: { slug: 'nordisia', title: 'Nordisia', category: 'Companies founded',
          theme: 'Capital · Real estate', role: 'Co-founder', status: 'Active', year: '2024 →',
          description: 'A platform matching Nordic private capital with high-performing real estate development at institutional standards.',
          href: 'https://nordisia.se/' } },
      { slug: 'secondry', kind: 'company', name: 'Secondry',
        built: 'The gateway to private market secondaries.',
        description: 'Building the secondary market for Nordic private holdings. The layer that has been missing for two decades.',
        year: '2025 →', status: 'Active',
        image: '',
        href: 'https://www.secondry.com/',
        reveal: { slug: 'secondry', title: 'Secondry', category: 'Companies founded',
          theme: 'Private secondaries', role: 'Co-founder', status: 'Active', year: '2025 →',
          description: 'The gateway to Nordic private market secondaries. Building the layer that has been missing for two decades.',
          href: 'https://www.secondry.com/' } },
      { slug: 'snoboll', kind: 'company', name: 'Snöboll',
        built: 'Invest together with the angels building the Nordic market.',
        description: 'The rails Nordic angels use to invest as a group. Terms, allocation, follow-on, all in one place.',
        year: '2024 →', status: 'Active',
        image: '',
        href: 'https://nordicangels.com/',
        reveal: { slug: 'snoboll', title: 'Snöboll', category: 'Companies founded',
          theme: 'Angel co-investing', role: 'Co-founder', status: 'Active', year: '2024 →',
          description: 'The rails Nordic angels use to invest as a group. Terms, allocation, follow-on, syndicates and SPVs in one place.' } },
      { slug: 'angel-advisory', kind: 'company', name: 'Angel Advisory',
        built: 'Bridging the angel world with corporate finance.',
        description: 'Advisory for the moment angel-backed companies graduate to institutional rounds, M&A, and beyond.',
        year: '2024 →', status: 'Active',
        image: '',
        href: 'https://angeladvisory.com/',
        reveal: { slug: 'angel-advisory', title: 'Angel Advisory', category: 'Companies founded',
          theme: 'Corporate finance', role: 'Co-founder', status: 'Active', year: '2024 →',
          description: 'Bridging the angel world with corporate finance. Advisory for the moment angel-backed companies graduate to institutional rounds, M&A, and beyond. Operates as Nordic Angel Office and Nordic Corporate Finance.',
          href: 'https://angeladvisory.com/' } },
      { slug: 'it-consulting', kind: 'company', name: 'IT Consulting Company',
        built: 'Built from scratch. Scaled. Exited.',
        description: '13 years building and scaling an IT consulting business in the Nordics. Exited in 2021. The company that taught the playbook.',
        year: '2008–2021', status: 'Exit',
        image: '',
        href: '#', muted: true,
        reveal: { slug: 'it-consulting', title: 'IT Consulting Company', category: 'Companies founded',
          theme: 'IT services', role: 'Founder · Operator', status: 'Exit', year: '2008–2021',
          description: '13 years building and scaling an IT consulting business in the Nordics. Exited in 2021. The company that taught the playbook.' } },

      // --- Current Portfolio --------------------------------------------
      { slug: 'cellcolabs', kind: 'portfolio', name: 'Cellcolabs',
        built: 'Stem cell therapeutics at scale.',
        description: 'Manufacturing high-quality stem cells for clinical research and longevity medicine.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://cellcolabs.com/',
        reveal: { slug: 'cellcolabs', title: 'Cellcolabs', category: 'Current portfolio',
          theme: 'Longevity · Biotech', role: 'Investor', status: 'Active',
          description: 'Manufacturing high-quality stem cells for clinical research and longevity medicine. One of the Nordic bets at the intersection of biotech and the longevity thesis.',
          href: 'https://cellcolabs.com/' } },
      { slug: 'redpine-ai', kind: 'portfolio', name: 'Redpine AI',
        built: 'Applied AI for the industrial Nordics.',
        description: 'Operational AI for industrial workflows in the Nordic market.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://www.redpine.ai/',
        reveal: { slug: 'redpine-ai', title: 'Redpine AI', category: 'Current portfolio',
          theme: 'Applied AI', role: 'Investor', status: 'Active',
          description: 'Applied AI for industrial workflows in the Nordic market.',
          href: 'https://www.redpine.ai/' } },
      { slug: 'smartports', kind: 'portfolio', name: 'Smartports',
        built: 'Solar canopies with EV charging.',
        description: 'Solar-powered parking canopies with integrated EV charging for commercial properties.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://smartports.se/',
        reveal: { slug: 'smartports', title: 'Smartports', category: 'Current portfolio',
          theme: 'Energy · Mobility infrastructure', role: 'Investor', status: 'Active',
          description: 'Solar-powered parking canopies with integrated EV charging, financed and built on commercial properties. Turning underused parking into renewable generation and mobility infrastructure.',
          href: 'https://smartports.se/' } },
      { slug: 'husa', kind: 'portfolio', name: 'Huså',
        built: 'A new Nordic destination.',
        description: 'Building a hospitality and lifestyle destination in the Swedish mountains.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://www.gruvbacken.se/',
        reveal: { slug: 'husa', title: 'Huså', category: 'Current portfolio',
          theme: 'Hospitality · Real estate', role: 'Investor', status: 'Active',
          description: 'Building a hospitality and lifestyle destination in the Swedish mountains.',
          href: 'https://www.gruvbacken.se/' } },
      { slug: 'exaum', kind: 'portfolio', name: 'Exaum',
        built: 'Energy-aware compute.',
        description: 'Energy and infrastructure for the next compute cycle.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://www.exaum.com/',
        reveal: { slug: 'exaum', title: 'Exaum', category: 'Current portfolio',
          theme: 'Energy · Compute', role: 'Investor', status: 'Active',
          description: 'Energy and infrastructure for the next compute cycle.',
          href: 'https://www.exaum.com/' } },
      { slug: 'mioo', kind: 'portfolio', name: 'Mioo',
        built: 'Consumer brand with intent.',
        description: 'Building a Nordic consumer brand at the intersection of design and everyday utility.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://mioo.cc/',
        reveal: { slug: 'mioo', title: 'Mioo', category: 'Current portfolio',
          theme: 'Consumer', role: 'Investor', status: 'Active',
          description: 'A Nordic consumer brand at the intersection of design and everyday utility.',
          href: 'https://mioo.cc/' } },
      { slug: 'cinode', kind: 'portfolio', name: 'Cinode',
        built: 'Skills infrastructure for consultancies.',
        description: 'The skills graph that runs underneath modern consulting organisations.',
        year: 'Active', status: 'Active',
        image: '',
        href: 'https://www.cinode.com/',
        reveal: { slug: 'cinode', title: 'Cinode', category: 'Current portfolio',
          theme: 'B2B SaaS · Skills graph', role: 'Investor', status: 'Active',
          description: 'The skills graph that runs underneath modern consulting organisations. A natural extension of the IT consulting playbook.',
          href: 'https://www.cinode.com/' } },
      { slug: 'identisure', kind: 'portfolio', name: 'Identisure',
        built: 'Trust infrastructure for digital identity.',
        description: 'Identity verification infrastructure for the Nordic market.',
        year: 'Active', status: 'Active',
        image: '',
        href: '#',
        reveal: { slug: 'identisure', title: 'Identisure', category: 'Current portfolio',
          theme: 'Identity · Trust', role: 'Investor', status: 'Active',
          description: 'Identity verification infrastructure for the Nordic market.' } },

      // --- Selected Exits -----------------------------------------------
      { slug: 'one-agency', kind: 'exit', name: 'One Agency',
        built: 'Nordic IT consulting platform.',
        description: 'Consultancy group built and exited as part of the long-running Nordic IT services thesis.',
        year: '— Exit', status: 'Exit',
        image: '',
        href: '#', muted: true,
        reveal: { slug: 'one-agency', title: 'One Agency', category: 'Selected exits',
          theme: 'IT services', role: 'Operator · Founder', status: 'Exit',
          description: 'Nordic IT consulting platform built and scaled as part of the long-running services thesis. Exited.' } },
      { slug: 'savr', kind: 'exit', name: 'SAVR',
        built: 'Re-engineered fund investing.',
        description: 'Fintech that rebuilt the way Nordic consumers buy investment funds. Exited.',
        year: '— Exit', status: 'Exit',
        image: '',
        href: 'https://savr.com/sv', muted: true,
        reveal: { slug: 'savr', title: 'SAVR', category: 'Selected exits',
          theme: 'Fintech · Asset management', role: 'Investor', status: 'Exit',
          description: 'Re-engineered fund investing for Nordic consumers. The category-defining bet on transparent, low-cost fund distribution. Exited.',
          href: 'https://savr.com/sv' } },

      // --- Initiatives within Nordic Angels -----------------------------
      { slug: 'angel-prize', kind: 'initiative', name: 'Angel Prize',
        built: 'Europe’s annual investor gala.',
        description: 'The yearly stage that recognises the angels and operators shaping European private capital.',
        year: '2021 →', status: 'Active',
        image: '',
        href: 'https://www.angelprize.com/',
        reveal: { slug: 'angel-prize', title: 'Angel Prize', category: 'Initiatives within Nordic Angels',
          theme: 'Recognition · Community', role: 'Co-founder', status: 'Active', year: '2021 →',
          description: 'Europe’s annual investor gala. The yearly stage that recognises the angels and operators shaping European private capital.',
          href: 'https://www.angelprize.com/' } },
      { slug: 'davos-angels', kind: 'initiative', name: 'Davos Angels',
        built: 'The angels who go to Davos.',
        description: 'An annual gathering bringing leading European angels to Davos during World Economic Forum week.',
        year: '2024 →', status: 'Active',
        image: '',
        href: 'https://davosangels.co/',
        reveal: { slug: 'davos-angels', title: 'Davos Angels', category: 'Initiatives within Nordic Angels',
          theme: 'Convening · Cross-border', role: 'Co-founder', status: 'Active', year: '2024 →',
          description: 'An annual gathering bringing leading European angels to Davos during World Economic Forum week.',
          href: 'https://davosangels.co/' } },
      { slug: 'state-of-european-angels', kind: 'initiative', name: 'State of European Angels',
        built: 'The annual benchmark on European angel investing. With BCG.',
        description: 'Initiated with Boston Consulting Group. Quantitative market data plus insights from leading angels across the continent.',
        year: '2024 →', status: 'Active',
        image: '',
        href: 'https://www.stateofeuropeanangels.com/',
        reveal: { slug: 'state-of-european-angels', title: 'State of European Angels', category: 'Initiatives within Nordic Angels',
          theme: 'Research · Insight reports', role: 'Initiator', status: 'Active', year: '2024 →',
          description: 'The annual benchmark on European angel investing, initiated with Boston Consulting Group. Quantitative market data plus insights from leading angels across the continent.',
          href: 'https://www.stateofeuropeanangels.com/' } },
      { slug: 'patric-blir-angel', kind: 'initiative', name: 'Patric blir Ängel',
        built: 'The podcast that demystifies angel investing.',
        description: 'Following Patric Edhagen on his journey into the startup world. Conversations with founders and angels across the Nordics.',
        year: '2022 →', status: 'Active',
        image: '',
        href: 'https://www.patricblirangel.se/',
        reveal: { slug: 'patric-blir-angel', title: 'Patric blir Ängel', category: 'Initiatives within Nordic Angels',
          theme: 'Media · Podcast', role: 'Producer', status: 'Active', year: '2022 →',
          description: 'The podcast that demystifies angel investing. Following Patric Edhagen on his journey into the startup world. Conversations with founders and angels across the Nordics.',
          href: 'https://www.patricblirangel.se/' } },

      // --- Early Bets & Advisory ----------------------------------------
      { slug: 'academic-work', kind: 'bet', name: 'Academic Work',
        built: 'Scandinavia’s largest staffing company.',
        description: 'Backed in 2001. Now Scandinavia’s largest staffing company. The bet that defined an asset class and a career.',
        year: '2001 →', status: 'Active',
        image: '',
        href: 'https://www.academicwork.se/',
        reveal: { slug: 'academic-work', title: 'Academic Work', category: 'Early bets & advisory',
          theme: 'Staffing · Talent', role: 'Early investor', status: 'Active', year: '2001 →',
          description: 'Backed in 2001. Now Scandinavia’s largest staffing company. The bet that defined an asset class and a career.',
          href: 'https://www.academicwork.se/' } },
      { slug: 'superhuman', kind: 'bet', name: 'Superhuman.net',
        built: 'A network shaping the future of longevity, science, technology, and human evolution.',
        description: 'Advisory role within Super Human Network. An exclusive gathering of global visionaries exploring longevity science, technology, and the future of human evolution.',
        year: 'Ongoing', status: 'Active',
        image: '',
        href: 'https://superhuman.net/',
        reveal: { slug: 'superhuman', title: 'Superhuman.net', category: 'Early bets & advisory',
          theme: 'Longevity · Network', role: 'Advisor', status: 'Active', year: 'Ongoing',
          description: 'Advisory role within Super Human Network. An exclusive gathering of global visionaries exploring longevity science, technology, and the future of human evolution.',
          href: 'https://superhuman.net/' } },
    ] satisfies readonly Case[],
  },

  roadAhead: {
    eyebrow: 'Current direction',
    items: [
      { text: 'Building institutional bridges between angels and the capital that scales them.' },
      { text: 'Scaling Angel House as the operational base for the Nordic capital community.' },
      { text: 'Cross-border infrastructure across Stockholm, Oslo, Copenhagen, and Helsinki.' },
      { text: 'Institutional investor relations through Nordic Angels at European scale.' },
    ],
  },

  contact: {
    line: "Let's build something.",
  },

  footer: {
    left:  'Jakobsbergsgatan 27 · 111 14 Stockholm',
    right: 'Built with intention.',
  },
} as const;
